import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 課程筆記 Sidebar
 *
 * Docusaurus 會自動讀取 docs/lessons/
 * 新增 lesson-004.md、lesson-005.md...
 * 不需要手動修改這裡。
 */
const sidebars: SidebarsConfig = {
  lessonsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'lessons',
    },
  ],
};

export default sidebars;