import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 課程筆記與文法單字庫 Sidebar 設定
 */
const sidebars: SidebarsConfig = {
  lessonsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'lessons',
    },
  ],
  referenceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'reference',
    },
  ],
};

export default sidebars;